# Generated by Django 4.0 on 2022-01-08 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_alter_register_mobile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='register',
            name='firstname',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
